MONGODB_HOST: mongodb-{{ env }}.dawsc.fun # mongodb-dev.dawsc.fun
REDIS_HOST: redis-{{ env }}.dawsc.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.dawsc.fun
CART_HOST: cart.backend-alb-{{ env }}.dawsc.fun
USER_HOST: user.backend-alb-{{ env }}.dawsc.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.dawsc.fun
MYSQL_HOST: mysql-{{ env }}.dawc.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.dawc.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.dawc.fun